---

- name: copy letsencrypt cli config file
  copy:
    src: letsencrypt/cli.ini
    dest: /etc/letsencrypt/cli.ini
    owner: root
    group: root
    mode: 0644

- name: create auto renewal systemd service
  copy:
    src: "letsencrypt/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - certbot.service
    - certbot.timer

- name: request SSL cert via certbot
  tags: [ request_ssl_certificate ]
  command: certbot --non-interactive -c /etc/letsencrypt/cli.ini certonly -d {{ item.domain }}
  with_items:
    - "{{ nginx_domains }}"

- name: enable certbot renewal service
  tags: [ vagrant_skip ]
  systemd:
    name: certbot.service
    state: started
    daemon_reload: yes
    enabled: yes
    masked: no

