---

- name: install enviroment php
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
    force: yes
  with_items:
    - php7.0
    - php7.0-fpm
    - php7.0-mysql
