---

- name: Install Wazuh repository key
  apt_key: url=https://packages.wazuh.com/key/GPG-KEY-WAZUH

- name: Add Wazuh repository
  apt_repository:
    repo: deb https://packages.wazuh.com/3.x/apt/ stable main
    state: present
    update_cache: yes

- name: Install Wazuh agent
  apt:
    name: wazuh-agent
    state: present
    update_cache: yes