---

- name: Install Wazuh repository key
  apt_key: url=https://packages.wazuh.com/key/GPG-KEY-WAZUH

- name: Add Wazuh repository
  apt_repository:
    repo: deb https://packages.wazuh.com/3.x/apt/ stable main
    state: present
    update_cache: yes

- name: Install Wazuh manager
  apt:
    name: wazuh-manager
    state: present
    update_cache: yes

- name: Restart service Wazuh manager
  service:
    name: wazuh-manager
    state: restarted

- name: Install Nodejs repository key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install Nodejs
  apt:
    name: nodejs
    state: present

- name: Install Wazuh API
  apt:
    name: wazuh-api
    state: present

- name: Restart service Wazuh APi
  service:
    name: wazuh-api
    state: restarted



