---
# Pre-setup tasks: install python for Ansible
- hosts: all
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal) &&
        sudo apt-add-repository universe && sudo apt-get -qq -y update && sudo apt-get install -q -y python-dev
        python-simplejson python-apt lsb-release python-pip apt-transport-https
      register: output
      changed_when: output.stdout != ""
    - name: gather facts for next task
      setup:
  tasks: []

- hosts: all
  tags: [common]
  roles:
    - common

- hosts: monitor
  tags: [monitor]
  roles:
    - monitor