---
# Pre-setup tasks: install python for Ansible
- hosts: all
  gather_facts: True
  pre_tasks:
    - name: install python for Ansible
      raw: sudo apt-get -qq -y update && sudo apt-get install -q -y python python-minimal python-dev python-simplejson python-apt lsb-release python-pip apt-transport-https
      changed_when: False
    - name: gather facts for next task
      setup:
  tasks: []

- hosts: all
  tags: [common]
  roles:
    - common

- hosts: monitor
  tags: [monitor]
  roles:
    - monitor